[Checkpoint 1]
CARBON-Super-Bootcamp/22-service-observability pull request #4
Opened 2021-02-18 07:57 UTC by aikuci

- Logging with winston was done

Note:
- If wanna check error output
-- Run service without turn on the other service such as: db, nats, redis, minIO

2021-02-18 23:03 UTC, aikuci commented
[task-service_error.log](https://github.com/CARBON-Super-Bootcamp/22-service-observability/files/6006434/task-service_error.log)
Add Attachment
sample Log file

2021-02-19 00:04 UTC, masdimya requested changes
Tambahkan log juga didalam setiap service, seperti service yang error 400 dan 500

2021-02-19 00:44 UTC, masdimya approved these changes

2021-02-19 00:45 UTC, merged

2021-02-19 01:58 UTC, aikuci commented
#1